services:

  mosquitto:
    image: eclipse-mosquitto:latest
    networks:
     - ragpipes
    volumes:
      - ./resources/mosquitto/config:/mosquitto/config:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - "1883:1883"

  pgvector:
    image: pgvector/pgvector:pg17
    networks:
     - ragpipes
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgvector
      PGDATA: /data/postgres
    volumes:
      - pgvector_data:/data/postgres
    ports:
      - "5432:5432"

  loader-text:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    networks:
      - ragpipes
    env_file:
      - .env
    environment:
     - RAGPIPES_MQTT__HANDLER=loader.text
     - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/loader/text/command
     - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/chunker/default/command

  loader-web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    networks:
      - ragpipes
    env_file:
      - .env
    environment:
     - RAGPIPES_MQTT__HANDLER=loader.web
     - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/loader/web/command
     - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/chunker/default/command

  loader-wikipedia:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
     - mosquitto
    networks:
      - ragpipes
    env_file:
      - .env
    environment:
     - RAGPIPES_MQTT__HANDLER=loader.wikipedia
     - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/loader/wikipedia/command
     - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/chunker/default/command

  translate-llmtranslate-de:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    networks:
      - ragpipes
    env_file:
      - .env
    environment:
     - RAGPIPES_MQTT__HANDLER=translate.llmtranslate
     - RAGPIPES_TRANSLATE__LANGUAGE=de
     - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/translate/de/command
     - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/translate/de/response

  translate-llmtranslate-fr:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    networks:
      - ragpipes
    env_file:
      - .env
    environment:
     - RAGPIPES_MQTT__HANDLER=translate.llmtranslate
     - RAGPIPES_TRANSLATE__LANGUAGE=fr
     - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/translate/fr/command
     - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/translate/fr/response

  chunker-default:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    networks:
      - ragpipes
    env_file:
      - .env
    environment:
     - RAGPIPES_MQTT__HANDLER=chunker
     - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/chunker/default/command
     - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/chunker/default/response
     - RAGPIPES_CHUNKER__CHUNK_SIZE=300
     - RAGPIPES_CHUNKER__CHUNK_OVERLAP=30

  vectorstore-default:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    networks:
      - ragpipes
    env_file:
      - .env
    environment:
    - RAGPIPES_MQTT__HANDLER=vectorstore
    - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/chunker/default/response
    - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/vectorstore/default/response
    - RAGPIPES_PGVECTOR__COLLECTION=default

  chat-default:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
      - pgvector
    networks:
      - ragpipes
    env_file:
      - .env
    environment:
    - RAGPIPES_MQTT__HANDLER=chat
    - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/chat/default/command
    - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/chat/default/response
    - RAGPIPES_PGVECTOR__COLLECTION=default

volumes:
  mosquitto_data:
  mosquitto_log:
  pgvector_data:

networks:
  ragpipes:
    driver: bridge
