services:

  handler-loader-web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
     - RAGPIPE_MQTT__HANDLER=loader.web
     - RAGPIPE_MQTT__TOPIC_COMMAND=ragpipe/loader/web/command
     - RAGPIPE_MQTT__TOPIC_RESPONSE=ragpipe/chunker/alpha/command
  handler-loader-wikipedia:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
     - RAGPIPE_MQTT__HANDLER=loader.wikipedia
     - RAGPIPE_MQTT__TOPIC_COMMAND=ragpipe/loader/wikipedia/command
     - RAGPIPE_MQTT__TOPIC_RESPONSE=ragpipe/chunker/alpha/command

  handler-chunker-alpha:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
     - RAGPIPE_MQTT__HANDLER=chunker
     - RAGPIPE_MQTT__TOPIC_COMMAND=ragpipe/chunker/alpha/command
     - RAGPIPE_MQTT__TOPIC_RESPONSE=ragpipe/chunker/alpha/response
     - RAGPIPE_CHUNKER__CHUNK_SIZE=300
     - RAGPIPE_CHUNKER__CHUNK_OVERLAP=30

  handler-chunker-beta:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
     - RAGPIPE_MQTT__HANDLER=chunker
     - RAGPIPE_MQTT__TOPIC_COMMAND=ragpipe/chunker/beta/command
     - RAGPIPE_MQTT__TOPIC_RESPONSE=ragpipe/chunker/beta/response

  handler-vectorstore-alpha:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
    - RAGPIPE_MQTT__HANDLER=vectorstore
    - RAGPIPE_MQTT__TOPIC_COMMAND=ragpipe/chunker/alpha/response
    - RAGPIPE_MQTT__TOPIC_RESPONSE=ragpipe/vectorstore/alpha/response
    - RAGPIPE_PGVECTOR__COLLECTION=alpha

  handler-vectorstore-beta:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
    - RAGPIPE_MQTT__HANDLER=vectorstore
    - RAGPIPE_MQTT__TOPIC_COMMAND=ragpipe/chunker/beta/response
    - RAGPIPE_MQTT__TOPIC_RESPONSE=ragpipe/vectorstore/beta/response
    - RAGPIPE_PGVECTOR__COLLECTION=beta

  handler-chat-alpha:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
    - RAGPIPE_MQTT__HANDLER=chat
    - RAGPIPE_MQTT__TOPIC_COMMAND=ragpipe/chat/alpha/command
    - RAGPIPE_MQTT__TOPIC_RESPONSE=ragpipe/chat/alpha/response
    - RAGPIPE_PGVECTOR__COLLECTION=alpha

  handler-chat-beta:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
    - RAGPIPE_MQTT__HANDLER=chat
    - RAGPIPE_MQTT__TOPIC_COMMAND=ragpipe/chat/beta/command
    - RAGPIPE_MQTT__TOPIC_RESPONSE=ragpipe/chat/beta/response
    - RAGPIPE_PGVECTOR__COLLECTION=beta
