services:

  handler-loader-web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
     - RAGPIPE_MQTT__HANDLER=loader.web
     - RAGPIPE_MQTT__TOPIC_COMMAND=ragpipe/loader/web/command
     - RAGPIPE_MQTT__TOPIC_RESPONSE=ragpipe/chunk/alpha/command
  handler-loader-wikipedia:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
     - RAGPIPE_MQTT__HANDLER=loader.wikipedia
     - RAGPIPE_MQTT__TOPIC_COMMAND=ragpipe/loader/wikipedia/command
     - RAGPIPE_MQTT__TOPIC_RESPONSE=ragpipe/chunk/alpha/command

  handler-chunk-alpha:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
     - RAGPIPE_MQTT__HANDLER=chunk
     - RAGPIPE_MQTT__TOPIC_COMMAND=ragpipe/chunk/alpha/command
     - RAGPIPE_MQTT__TOPIC_RESPONSE=ragpipe/chunk/alpha/response

  handler-chunk-beta:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
     - RAGPIPE_MQTT__HANDLER=chunk
     - RAGPIPE_MQTT__TOPIC_COMMAND=ragpipe/chunk/beta/command
     - RAGPIPE_MQTT__TOPIC_RESPONSE=ragpipe/chunk/beta/response

  handler-vectorstore-alpha:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
    - RAGPIPE_MQTT__HANDLER=vectorstore
    - RAGPIPE_MQTT__TOPIC_COMMAND=ragpipe/chunk/alpha/response
    - RAGPIPE_MQTT__TOPIC_RESPONSE=ragpipe/vectorstore/alpha/response
    - RAGPIPE_PGVECTOR__COLLECTION=alpha

  handler-vectorstore-beta:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
    - RAGPIPE_MQTT__HANDLER=vectorstore
    - RAGPIPE_MQTT__TOPIC_COMMAND=ragpipe/chunk/beta/response
    - RAGPIPE_MQTT__TOPIC_RESPONSE=ragpipe/vectorstore/beta/response
    - RAGPIPE_PGVECTOR__COLLECTION=beta

  handler-chat-alpha:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
    - RAGPIPE_MQTT__HANDLER=chat
    - RAGPIPE_MQTT__TOPIC_COMMAND=ragpipe/chat/alpha/command
    - RAGPIPE_MQTT__TOPIC_RESPONSE=ragpipe/chat/alpha/response
    - RAGPIPE_PGVECTOR__COLLECTION=alpha

  handler-chat-beta:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
    - RAGPIPE_MQTT__HANDLER=chat
    - RAGPIPE_MQTT__TOPIC_COMMAND=ragpipe/chat/beta/command
    - RAGPIPE_MQTT__TOPIC_RESPONSE=ragpipe/chat/beta/response
    - RAGPIPE_PGVECTOR__COLLECTION=beta
