services:

  handler-loader-web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
     - RAGPIPES_MQTT__HANDLER=loader.web
     - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/loader/web/command
     - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/chunker/alpha/command

  handler-loader-wikipedia:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
     - RAGPIPES_MQTT__HANDLER=loader.wikipedia
     - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/loader/wikipedia/command
     - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/chunker/alpha/command

  handler-chunker-alpha:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
     - RAGPIPES_MQTT__HANDLER=chunker
     - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/chunker/alpha/command
     - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/chunker/alpha/response
     - RAGPIPES_CHUNKER__CHUNK_SIZE=300
     - RAGPIPES_CHUNKER__CHUNK_OVERLAP=30

  handler-chunker-beta:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
     - RAGPIPES_MQTT__HANDLER=chunker
     - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/chunker/beta/command
     - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/chunker/beta/response

  handler-vectorstore-alpha:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
    - RAGPIPES_MQTT__HANDLER=vectorstore
    - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/chunker/alpha/response
    - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/vectorstore/alpha/response
    - RAGPIPES_PGVECTOR__COLLECTION=alpha

  handler-vectorstore-beta:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
    - RAGPIPES_MQTT__HANDLER=vectorstore
    - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/chunker/beta/response
    - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/vectorstore/beta/response
    - RAGPIPES_PGVECTOR__COLLECTION=beta

  handler-chat-alpha:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
    - RAGPIPES_MQTT__HANDLER=chat
    - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/chat/alpha/command
    - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/chat/alpha/response
    - RAGPIPES_PGVECTOR__COLLECTION=alpha

  handler-chat-beta:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
    - RAGPIPES_MQTT__HANDLER=chat
    - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/chat/beta/command
    - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/chat/beta/response
    - RAGPIPES_PGVECTOR__COLLECTION=beta
