services:

  mosquitto:
    image: eclipse-mosquitto:latest
    networks:
     - ragpipes
    volumes:
      - ./resources/mosquitto/config:/mosquitto/config:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - "1883:1883"


  pgvector:
    image: pgvector/pgvector:pg17
    networks:
     - ragpipes
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgvector
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  loader-text:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    networks:
      - ragpipes
    env_file:
      - .env
    environment:
     - RAGPIPES_MQTT__HANDLER=loader.text
     - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/loader/text/command
     - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/chunker/alpha/command

  loader-web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    networks:
      - ragpipes
    env_file:
      - .env
    environment:
     - RAGPIPES_MQTT__HANDLER=loader.web
     - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/loader/web/command
     - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/chunker/alpha/command

  loader-wikipedia:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
     - mosquitto
    networks:
      - ragpipes
    env_file:
      - .env
    environment:
     - RAGPIPES_MQTT__HANDLER=loader.wikipedia
     - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/loader/wikipedia/command
     - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/chunker/alpha/command

  chunker-alpha:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    networks:
      - ragpipes
    env_file:
      - .env
    environment:
     - RAGPIPES_MQTT__HANDLER=chunker
     - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/chunker/alpha/command
     - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/chunker/alpha/response
     - RAGPIPES_CHUNKER__CHUNK_SIZE=300
     - RAGPIPES_CHUNKER__CHUNK_OVERLAP=30

  chunker-beta:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    networks:
      - ragpipes
    env_file:
      - .env
    environment:
     - RAGPIPES_MQTT__HANDLER=chunker
     - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/chunker/beta/command
     - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/chunker/beta/response

  vectorstore-alpha:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    networks:
      - ragpipes
    env_file:
      - .env
    environment:
    - RAGPIPES_MQTT__HANDLER=vectorstore
    - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/chunker/alpha/response
    - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/vectorstore/alpha/response
    - RAGPIPES_PGVECTOR__COLLECTION=alpha

  vectorstore-beta:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    networks:
      - ragpipes
    env_file:
      - .env
    environment:
    - RAGPIPES_MQTT__HANDLER=vectorstore
    - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/chunker/beta/response
    - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/vectorstore/beta/response
    - RAGPIPES_PGVECTOR__COLLECTION=beta

  chat-alpha:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
      - pgvector
    networks:
      - ragpipes
    env_file:
      - .env
    environment:
    - RAGPIPES_MQTT__HANDLER=chat
    - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/chat/alpha/command
    - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/chat/alpha/response
    - RAGPIPES_PGVECTOR__COLLECTION=alpha

  chat-beta:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
      - pgvector
    networks:
      - ragpipes
    env_file:
      - .env
    environment:
    - RAGPIPES_MQTT__HANDLER=chat
    - RAGPIPES_MQTT__TOPIC_COMMAND=ragpipes/chat/beta/command
    - RAGPIPES_MQTT__TOPIC_RESPONSE=ragpipes/chat/beta/response
    - RAGPIPES_PGVECTOR__COLLECTION=beta

volumes:
  mosquitto_data:
  mosquitto_log:
  pgvector_data:

networks:
  ragpipes:
    driver: bridge
