general:
  log_level: info

mqtt:
  # broker: localhost
  # port: 1883
  # username: user
  # password: password
  # keepalive: 60
  # handler: text
  # topic_command: ragpipe/command
  # topic_response: ragpipe/response

pgvector:
  # host: localhost
  # port: 5432
  # user: pgvector
  # password: pgvector
  # database: pgvector
  # collection: ragpipe

openai:
  # embedding_model: text-embedding-ada-002

chunking:
  # chunk_size: 200
  # chunk_overlap: 20
